### ISSUE TITLE
Question about number of clusters

### ISSUE THREAD

**Issue by cattired** [Yorko/bert-finetuning-catalyst#1]
Hey Yorko!

Thank you for the library and the youtube explanations, ran into it while exploring BERT!

Apologize in advance for a beginner question.

I'm trying to run your code on my data. However, it seems that I cannot specify anything but 5 clusters, otherwise the code crashes with 

  File "/home/svet/gitprojects/bert-finetuning-catalyst/venv/lib/python3.7/site-packages/torch/nn/functional.py", line 2265, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
IndexError: Target 4 is out of bounds.

(I have 4 clusters)

May be I missed something in your explanations but your sdg_id column has > 5 different values, this also confused me.

Would be really grateful if you responed.

Cheers,

**Comment by Yorko** [comment]
Hi, that's nothing to do with BERT or Catalyst, just the requirement of the criterion `torch.nn.CrossEntropyLoss` – you need to rename classes like 0, 1,... n-1 where n is the number of classes. I'm doing that with `class_dict` of the form {'class1': 0, 'class2': 1, 'class3': 2, ...} [here](https://github.com/Yorko/bert-finetuning-catalyst/blob/master/src/data.py#L44).
